[tool.poetry]
name = "streamlit-cheki"
version = "0.1.0"
description = ""
authors = ["Jonathan <jolin3apa@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
plotly = "^5.5.0"
gspread = "^5.1.1"
numpy = "^1.22.1"
google = "^3.0.0"
matplotlib = "^3.5.1"
streamlit = "^1.12.2"
validators = "0.18.2"
loguru = "^0.6.0"
pandas = "^2.0.1"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
pytest = "^6.2.5"
jupyter = "^1.0.0"

[tool.poetry.group.dev.dependencies]
mypy = "^0.991"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
